# Generated by Django 3.2.6 on 2021-08-25 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20210807_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=242)),
                ('locality', models.CharField(max_length=300)),
                ('area_and_street', models.CharField(max_length=840)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('landmark', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('Andra Pradesh', 'Andra Pradesh'), ('Arunalchal Pradesh', 'Arunacahl Pradesh'), ('Andaman', 'Andaman'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Karnataka', 'KArnataka'), ('Tamil Nadu', 'Tamil Nadu'), ('Kerala', 'Kerala'), ('Telengana', 'Telengana'), ('Jharkhand', 'Jharkhand'), ('Gujraj', 'Gujrrat'), ('Maharastra', 'Maharastara'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Nagaland', 'Nagaland'), ('Mizoram', 'Mizoram'), ('Punjab', 'Punjab'), ('J&K', 'J&K'), ('Himachal Pradesh', 'Hiamchal Pradesh'), ('Goa', 'Goa'), ('Tripura', 'Tripura'), ('Hariyana', 'Hariyana')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
