# Generated by Django 3.2.6 on 2021-08-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userdetails_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='pending', max_length=50),
        ),
    ]
