# Generated by Django 3.2.6 on 2021-08-31 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_orderplace_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplace',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userdetails'),
        ),
    ]
